stages:
  - lint
  - test

variables:
  PYTHON_VERSION: "3.10"

before_script:
  - apt-get update
  - apt-get install -y python3 python3-venv python3-pip
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

linting:
  stage: lint
  script:
    - pip install flake8
    - flake8 --max-line-length=88 functions.py test_functions.py

unit_tests:
  stage: test
  script:
    - pip install pytest
    - pytest tests/
