deploy_to_github:
  stage: deploy
  only: 
    - production
  script:
    # ✅ Ensure full Git history before checking out
    - git fetch --prune --unshallow || true

    # ✅ Checkout production BEFORE making any changes
    - git checkout production

    # ✅ Remove unnecessary files from production
    - rm -rf tests/ .gitignore requirements.txt .gitlab-ci.yml

    # ✅ Configure Git identity
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"

    # ✅ Prevent capturing dependency files
    - git ls-files -o -i --exclude-standard > .gitignore  # Ensure ignored files don't get added
    - git add -u  # ✅ Only add changes to already tracked files

    # ✅ Commit only if there are changes (prevents log overflow)
    - |
      git diff --staged --quiet || git commit -m 'chore: remove unnecessary files'

    # ✅ Ensure remote URL is always set correctly
    - git remote set-url github https://oauth2:${GITHUB_TOKEN}@github.com/ingega/big-shadow-trend.git

    # ✅ Push production → GitHub main (cleanly)
    - git push github production:main --force
