stages:
  - lint
  - test
  - deploy

variables:
  PYTHON_VERSION: "3.10"

before_script:
  - apt-get update && apt-get install -y python3 python3-venv python3-pip
  - python3 -m venv venv
  - venv/bin/python3 -m pip install --upgrade pip
  - venv/bin/python3 -m pip install -r requirements.txt flake8 pytest

linting:
  stage: lint
  script:
    - venv/bin/python3 -m flake8 --max-line-length=88 functions.py tests/test_functions.py

unit_tests:
  stage: test
  script:
    - venv/bin/python3 -m pytest tests/


deploy_to_github:
  stage: deploy
  only: 
    - production
  script:
    # ✅ Ensure full Git history before checking out
    - git fetch --prune --unshallow || true

    # ✅ Checkout production BEFORE making any changes
    - git checkout production

    # ✅ Remove unnecessary files from production
    - rm -rf tests/ .gitignore requirements.txt .gitlab-ci.yml

    # ✅ Configure Git identity
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"

    # ✅ Prevent capturing dependency files
    - git ls-files -o -i --exclude-standard > .gitignore  # Ensure ignored files don't get added
    - git add -u  # ✅ Only add changes to already tracked files

    # ✅ Commit only if there are changes (prevents log overflow)
    - |
      git diff --staged --quiet || git commit -m 'chore: remove unnecessary files'

    # ✅ Ensure GitHub remote exists before setting the URL
    - if ! git remote get-url github >/dev/null 2>&1; then git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/ingega/big-shadow-trend.git; fi
    - git remote set-url github https://oauth2:${GITHUB_TOKEN}@github.com/ingega/big-shadow-trend.git

    # ✅ Push production → GitHub main (cleanly)
    - git push github production:main --force
