stages:
  - lint
  - test

variables:
  PYTHON_VERSION: "3.10"

before_script:
  - apt-get update && apt-get install -y python3 python3-venv python3-pip
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt flake8 pytest

linting:
  stage: lint
  script:
    - source venv/bin/activate
    - flake8 --max-line-length=88 functions.py tests/test_functions.py

unit_tests:
  stage: test
  script:
    - source venv/bin/activate
    - export PYTHONPATH=$(pwd)
    - pytest tests/
