stages:
  - lint
  - test
  - deploy

variables:
  PYTHON_VERSION: "3.10"

before_script:
  - apt-get update && apt-get install -y python3 python3-venv python3-pip
  - python3 -m venv venv
  - venv/bin/python3 -m pip install --upgrade pip
  - venv/bin/python3 -m pip install -r requirements.txt flake8 pytest

linting:
  stage: lint
  script:
    - venv/bin/python3 -m flake8 --max-line-length=88 functions.py tests/test_functions.py

unit_tests:
  stage: test
  script:
    - venv/bin/python3 -m pytest tests/

deploy_to_github:
  stage: deploy
  only: 
    - production
  script:
    # Ensure full Git history before checking out
    - git fetch --prune --unshallow || true

    # change to production, no changes are commited yet
    - git checkout production

    # remove unnecessary files
    - rm -rf tests/ .gitignore requirements.txt .gitlab-ci.yml

    # Configure Git identity
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"

    # Ensure changes are committed safely
    - |
      git add -A
      git diff --cached --exit-code || git commit -m 'chore: remove unnecessary files'

    # Ensure remote URL is always set correctly
    - git remote set-url github https://oauth2:${GITHUB_TOKEN}@github.com/ingega/big-shadow-trend.git

    # Force push production → GitHub main
    - git push github production:main --force

