stages:
  - lint
  - test
  - deploy

variables:
  PYTHON_VERSION: "3.10"

before_script:
  - apt-get update && apt-get install -y python3 python3-venv python3-pip
  - python3 -m venv venv
  - venv/bin/python3 -m pip install --upgrade pip
  - venv/bin/python3 -m pip install -r requirements.txt flake8 pytest

linting:
  stage: lint
  script:
    - venv/bin/python3 -m flake8 --max-line-length=88 functions.py tests/test_functions.py

unit_tests:
  stage: test
  script:
    - venv/bin/python3 -m pytest tests/

deploy_to_github:
  stage: deploy
  only: 
    - production
  script:
    - rm -rf tests/ .gitignore requeriments.txt .gitlab-ci.yml
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote add github https://oauth2:${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}@github.com/ingega/big-shadow-trend.git || git remote set-url github https://oauth2:${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}@github.com/ingega/big-shadow-trend.git
    - git push github production
